package f.thp.tp3.actividad1.Ejercicio6_MusicAPP_LocalDate;

public enum TipoResultado {
	CANCION_ESCUCHADA, USUARIO_INEXISTENTE, CANCION_INEXISTENTE, LIMITE_ALCANZADO, CANCION_NO_DISPONIBLE, OPERACION_EXITOSA
}